const { buildEmailTemplate } = require('./emailService');
const Mailjet = require("node-mailjet");

// Mailjet configuration
const MAILJET_API_KEY = process.env.MJ_API_KEY;
const MAILJET_SECRET_KEY = process.env.MJ_SECRET_KEY;
const FROM_EMAIL = process.env.MJ_FROM_EMAIL;
const FROM_NAME = process.env.FROM_NAME || "AICONO EMS";

// Initialize Mailjet client
const mailjet = new Mailjet({
  apiKey: MAILJET_API_KEY,
  apiSecret: MAILJET_SECRET_KEY,
});

/**
 * Report Email Service
 * 
 * Formats and sends scheduled reports via email
 */
class ReportEmailService {
  /**
   * Send scheduled report email
   * @param {Object} recipient - ReportingRecipient object
   * @param {Object} building - Building object
   * @param {Object} reportData - Generated report data
   * @param {Object} reportConfig - Reporting configuration
   * @returns {Promise<Object>} Result object with success status
   */
  async sendScheduledReport(recipient, building, reportData, reportConfig) {
    try {
      if (!recipient || !recipient.email) {
        throw new Error('Recipient email is required');
      }

      // Format report as HTML and text
      const htmlContent = this.formatReportAsHTML(reportData, reportConfig, building);
      const textContent = this.formatReportAsText(reportData, reportConfig, building);

      // Send email
      const subject = `${reportConfig.name} - ${building.name}`;
      
      const request = mailjet.post("send", { version: "v3.1" }).request({
        Messages: [
          {
            From: {
              Email: FROM_EMAIL,
              Name: FROM_NAME,
            },
            To: [
              {
                Email: recipient.email,
                Name: recipient.name || recipient.email.split("@")[0],
              },
            ],
            Subject: subject,
            TextPart: textContent,
            HTMLPart: htmlContent,
          },
        ],
      });

      const result = await request;

      return {
        ok: true,
        messageId: result.body.Messages[0].To[0].MessageID,
        status: result.body.Messages[0].Status,
      };
    } catch (error) {
      console.error(`[REPORT-EMAIL] Error sending report to ${recipient?.email}:`, error.message);
      return {
        ok: false,
        error: error.message,
      };
    }
  }

  /**
   * Format report as HTML
   * @param {Object} reportData - Generated report data
   * @param {Object} reportConfig - Reporting configuration
   * @param {Object} building - Building object
   * @returns {String} HTML content
   */
  formatReportAsHTML(reportData, reportConfig, building) {
    const { contents, timeRange, kpis } = reportData;
    const { reportContents } = reportConfig;

    // Format time range
    const timeRangeStr = this.formatTimeRange(timeRange);

    // Build content sections
    let contentSections = '';

    // Summary section
    contentSections += this.formatSummarySection(reportData, building);

    // Generate each selected content section
    for (const contentType of reportContents) {
      const content = contents[contentType];
      if (content && !content.error) {
        contentSections += this.formatContentSection(contentType, content);
      }
    }

    const htmlContent = buildEmailTemplate({
      heading: "AICONO EMS",
      subheading: reportConfig.name,
      contentHtml: `
        <h2 style="color: #214A59; margin-top: 0;">${reportConfig.name}</h2>
        <div class="info-box">
          <strong>Building:</strong> ${building.name}<br>
          <strong>Report Period:</strong> ${timeRangeStr}<br>
          <strong>Generated:</strong> ${new Date().toLocaleString()}
        </div>
        ${contentSections}
        <div class="notice">
          <strong>📊 Report Information:</strong>
          <ul>
            <li>This is an automated ${reportConfig.interval.toLowerCase()} report from AICONO EMS.</li>
            <li>Data is based on aggregated measurements from your building's sensors.</li>
            <li>For detailed analysis, please visit the AICONO dashboard.</li>
          </ul>
        </div>
      `,
      footerLines: [
        `This ${reportConfig.interval.toLowerCase()} report was automatically generated by AICONO EMS.`,
        "If you have any questions, please contact your system administrator.",
      ],
    });

    return htmlContent;
  }

  /**
   * Format report as plain text
   * @param {Object} reportData - Generated report data
   * @param {Object} reportConfig - Reporting configuration
   * @param {Object} building - Building object
   * @returns {String} Plain text content
   */
  formatReportAsText(reportData, reportConfig, building) {
    const { contents, timeRange, kpis } = reportData;
    const { reportContents } = reportConfig;

    const timeRangeStr = this.formatTimeRange(timeRange);
    let text = `AICONO EMS - ${reportConfig.name}\n\n`;
    text += `Building: ${building.name}\n`;
    text += `Report Period: ${timeRangeStr}\n`;
    text += `Generated: ${new Date().toLocaleString()}\n\n`;
    text += `${'='.repeat(50)}\n\n`;

    // Summary
    text += `SUMMARY\n`;
    text += `Total Consumption: ${kpis.total_consumption} ${kpis.unit}\n`;
    text += `Average: ${kpis.average} ${kpis.unit}\n`;
    text += `Peak: ${kpis.peak} ${kpis.unit}\n\n`;

    // Content sections
    for (const contentType of reportContents) {
      const content = contents[contentType];
      if (content && !content.error) {
        text += this.formatContentSectionText(contentType, content);
      }
    }

    text += `\n${'='.repeat(50)}\n`;
    text += `This ${reportConfig.interval.toLowerCase()} report was automatically generated by AICONO EMS.\n`;
    text += `If you have any questions, please contact your system administrator.\n`;

    return text;
  }

  /**
   * Format time range string
   */
  formatTimeRange(timeRange) {
    const start = new Date(timeRange.start).toLocaleDateString();
    const end = new Date(timeRange.end).toLocaleDateString();
    return `${start} to ${end}`;
  }

  /**
   * Format summary section
   */
  formatSummarySection(reportData, building) {
    const { kpis } = reportData;
    return `
      <div class="info-box">
        <h3 style="color: #214A59; margin-top: 0;">Summary</h3>
        <table style="width: 100%; border-collapse: collapse;">
          <tr>
            <td style="padding: 8px; border-bottom: 1px solid #eee;"><strong>Total Consumption:</strong></td>
            <td style="padding: 8px; border-bottom: 1px solid #eee;">${kpis.total_consumption} ${kpis.unit}</td>
          </tr>
          <tr>
            <td style="padding: 8px; border-bottom: 1px solid #eee;"><strong>Average:</strong></td>
            <td style="padding: 8px; border-bottom: 1px solid #eee;">${kpis.average} ${kpis.unit}</td>
          </tr>
          <tr>
            <td style="padding: 8px; border-bottom: 1px solid #eee;"><strong>Peak:</strong></td>
            <td style="padding: 8px; border-bottom: 1px solid #eee;">${kpis.peak} ${kpis.unit}</td>
          </tr>
          <tr>
            <td style="padding: 8px;"><strong>Data Quality:</strong></td>
            <td style="padding: 8px;">${kpis.average_quality}% ${kpis.data_quality_warning ? '⚠️' : '✓'}</td>
          </tr>
        </table>
      </div>
    `;
  }

  /**
   * Format content section HTML
   */
  formatContentSection(contentType, content) {
    switch (contentType) {
      case 'TotalConsumption':
        return `
          <div class="info-box">
            <h3 style="color: #214A59; margin-top: 0;">Total Consumption</h3>
            <p><strong>Total:</strong> ${content.totalConsumption} ${content.unit}</p>
            <p><strong>Average:</strong> ${content.average} ${content.unit}</p>
            <p><strong>Peak:</strong> ${content.peak} ${content.unit}</p>
          </div>
        `;

      case 'ConsumptionByRoom':
        if (!content.rooms || content.rooms.length === 0) {
          return `<div class="info-box"><p>No room data available.</p></div>`;
        }
        let roomsHtml = '<table style="width: 100%; border-collapse: collapse; margin-top: 10px;"><tr style="background: #f8f9fa;"><th style="padding: 8px; text-align: left;">Room</th><th style="padding: 8px; text-align: right;">Consumption</th><th style="padding: 8px; text-align: right;">Average</th></tr>';
        content.rooms.slice(0, 10).forEach(room => {
          roomsHtml += `<tr><td style="padding: 8px; border-bottom: 1px solid #eee;">${room.roomName}</td><td style="padding: 8px; text-align: right; border-bottom: 1px solid #eee;">${room.consumption} ${room.unit}</td><td style="padding: 8px; text-align: right; border-bottom: 1px solid #eee;">${room.average} ${room.unit}</td></tr>`;
        });
        roomsHtml += '</table>';
        return `
          <div class="info-box">
            <h3 style="color: #214A59; margin-top: 0;">Consumption by Room</h3>
            ${roomsHtml}
          </div>
        `;

      case 'PeakLoads':
        return `
          <div class="info-box">
            <h3 style="color: #214A59; margin-top: 0;">Peak Loads</h3>
            <p><strong>Peak:</strong> ${content.peak} ${content.unit}</p>
            <p><strong>Average:</strong> ${content.average} ${content.unit}</p>
            ${content.peakToAverageRatio ? `<p><strong>Peak to Average Ratio:</strong> ${content.peakToAverageRatio}x</p>` : ''}
          </div>
        `;

      case 'MeasurementTypeBreakdown':
        if (!content.breakdown || content.breakdown.length === 0) {
          return `<div class="info-box"><p>No breakdown data available.</p></div>`;
        }
        let breakdownHtml = '<table style="width: 100%; border-collapse: collapse; margin-top: 10px;"><tr style="background: #f8f9fa;"><th style="padding: 8px; text-align: left;">Type</th><th style="padding: 8px; text-align: right;">Total</th><th style="padding: 8px; text-align: right;">Average</th></tr>';
        content.breakdown.forEach(item => {
          breakdownHtml += `<tr><td style="padding: 8px; border-bottom: 1px solid #eee;">${item.measurement_type}</td><td style="padding: 8px; text-align: right; border-bottom: 1px solid #eee;">${item.total} ${item.unit}</td><td style="padding: 8px; text-align: right; border-bottom: 1px solid #eee;">${item.average} ${item.unit}</td></tr>`;
        });
        breakdownHtml += '</table>';
        return `
          <div class="info-box">
            <h3 style="color: #214A59; margin-top: 0;">Measurement Type Breakdown</h3>
            ${breakdownHtml}
          </div>
        `;

      case 'EUI':
        if (!content.available) {
          return `<div class="info-box"><p>${content.message || 'EUI data not available'}</p></div>`;
        }
        return `
          <div class="info-box">
            <h3 style="color: #214A59; margin-top: 0;">Energy Use Intensity (EUI)</h3>
            <p><strong>EUI:</strong> ${content.eui} ${content.unit}</p>
            <p><strong>Total Consumption:</strong> ${content.totalConsumption} kWh</p>
            <p><strong>Heated Area:</strong> ${content.heatedArea} m²</p>
          </div>
        `;

      case 'PerCapitaConsumption':
        if (!content.available) {
          return `<div class="info-box"><p>${content.message || 'Per capita data not available'}</p></div>`;
        }
        return `
          <div class="info-box">
            <h3 style="color: #214A59; margin-top: 0;">Per Capita Consumption</h3>
            <p><strong>Per Capita:</strong> ${content.perCapita} ${content.unit}</p>
            <p><strong>Total Consumption:</strong> ${content.totalConsumption} kWh</p>
            <p><strong>Number of People:</strong> ${content.numPeople}</p>
          </div>
        `;

      case 'BenchmarkComparison':
        if (!content.available) {
          return `<div class="info-box"><p>${content.message || 'Benchmark comparison not available'}</p></div>`;
        }
        const statusColor = content.status === 'Below Target' ? '#28a745' : content.status === 'Above Target' ? '#dc3545' : '#ffc107';
        return `
          <div class="info-box">
            <h3 style="color: #214A59; margin-top: 0;">Benchmark Comparison</h3>
            <p><strong>Building EUI:</strong> ${content.buildingEUI} kWh/m²</p>
            <p><strong>Target EUI:</strong> ${content.targetEUI} kWh/m²</p>
            <p><strong>Difference:</strong> ${content.difference} kWh/m² (${content.percentageDifference}%)</p>
            <p><strong>Status:</strong> <span style="color: ${statusColor};">${content.status}</span></p>
            <p><strong>Type of Use:</strong> ${content.typeOfUse}</p>
          </div>
        `;

      case 'InefficientUsage':
        return `
          <div class="info-box">
            <h3 style="color: #214A59; margin-top: 0;">Inefficient Usage Analysis</h3>
            <p><strong>Base Load:</strong> ${content.baseLoad} kWh</p>
            <p><strong>Average Load:</strong> ${content.averageLoad} kWh</p>
            ${content.baseToAverageRatio ? `<p><strong>Base to Average Ratio:</strong> ${content.baseToAverageRatio}</p>` : ''}
            <p><strong>Status:</strong> ${content.inefficientUsageDetected ? '⚠️ ' + content.message : '✓ ' + content.message}</p>
          </div>
        `;

      case 'Anomalies':
        return `
          <div class="info-box">
            <h3 style="color: #214A59; margin-top: 0;">Anomalies Detected</h3>
            <p><strong>Total Anomalies:</strong> ${content.total}</p>
            <p><strong>By Severity:</strong> High: ${content.bySeverity.High}, Medium: ${content.bySeverity.Medium}, Low: ${content.bySeverity.Low}</p>
            ${content.anomalies && content.anomalies.length > 0 ? `
              <p><strong>Recent Anomalies:</strong></p>
              <ul>
                ${content.anomalies.slice(0, 5).map(anomaly => 
                  `<li>${new Date(anomaly.timestamp).toLocaleString()}: ${anomaly.sensorName} - ${anomaly.violatedRule} (${anomaly.severity})</li>`
                ).join('')}
              </ul>
            ` : ''}
          </div>
        `;

      case 'PeriodComparison':
        return `
          <div class="info-box">
            <h3 style="color: #214A59; margin-top: 0;">Period Comparison</h3>
            <p><strong>Current Period Consumption:</strong> ${content.current.consumption} kWh</p>
            <p><strong>Previous Period Consumption:</strong> ${content.previous.consumption} kWh</p>
            <p><strong>Change:</strong> ${content.change.consumption} kWh (${content.change.consumptionPercent}%)</p>
            ${content.change.consumptionPercent > 0 ? '<p style="color: #dc3545;">⚠️ Consumption increased</p>' : content.change.consumptionPercent < 0 ? '<p style="color: #28a745;">✓ Consumption decreased</p>' : '<p>No change</p>'}
          </div>
        `;

      case 'TimeBasedAnalysis':
        return `
          <div class="info-box">
            <h3 style="color: #214A59; margin-top: 0;">Time-Based Analysis</h3>
            <p><strong>Day Consumption:</strong> ${content.dayNight.day} kWh (${content.dayNight.dayPercentage}%)</p>
            <p><strong>Night Consumption:</strong> ${content.dayNight.night} kWh</p>
            <p><strong>Weekday Consumption:</strong> ${content.weekdayWeekend.weekday} kWh (${content.weekdayWeekend.weekdayPercentage}%)</p>
            <p><strong>Weekend Consumption:</strong> ${content.weekdayWeekend.weekend} kWh</p>
          </div>
        `;

      case 'BuildingComparison':
        if (!content.available) {
          return `<div class="info-box"><p>${content.message || 'Building comparison not available'}</p></div>`;
        }
        let buildingsHtml = '<table style="width: 100%; border-collapse: collapse; margin-top: 10px;"><tr style="background: #f8f9fa;"><th style="padding: 8px; text-align: left;">Building</th><th style="padding: 8px; text-align: right;">Consumption</th><th style="padding: 8px; text-align: right;">EUI</th></tr>';
        content.buildings.forEach(b => {
          buildingsHtml += `<tr><td style="padding: 8px; border-bottom: 1px solid #eee;">${b.buildingName}</td><td style="padding: 8px; text-align: right; border-bottom: 1px solid #eee;">${b.consumption} kWh</td><td style="padding: 8px; text-align: right; border-bottom: 1px solid #eee;">${b.eui !== null ? b.eui + ' kWh/m²' : 'N/A'}</td></tr>`;
        });
        buildingsHtml += '</table>';
        return `
          <div class="info-box">
            <h3 style="color: #214A59; margin-top: 0;">Building Comparison</h3>
            ${buildingsHtml}
          </div>
        `;

      case 'TemperatureAnalysis':
        if (!content.available) {
          return `<div class="info-box"><p>${content.message || 'Temperature analysis not available'}</p></div>`;
        }
        return `
          <div class="info-box">
            <h3 style="color: #214A59; margin-top: 0;">Temperature Analysis</h3>
            <p><strong>Overall Average:</strong> ${content.overall.average} ${content.overall.unit}</p>
            <p><strong>Overall Min:</strong> ${content.overall.min} ${content.overall.unit}</p>
            <p><strong>Overall Max:</strong> ${content.overall.max} ${content.overall.unit}</p>
            <p><strong>Total Sensors:</strong> ${content.totalSensors}</p>
          </div>
        `;

      case 'DataQualityReport':
        const qualityColor = content.status === 'Excellent' ? '#28a745' : content.status === 'Good' ? '#17a2b8' : content.status === 'Fair' ? '#ffc107' : '#dc3545';
        return `
          <div class="info-box">
            <h3 style="color: #214A59; margin-top: 0;">Data Quality Report</h3>
            <p><strong>Average Quality:</strong> <span style="color: ${qualityColor};">${content.averageQuality}%</span></p>
            <p><strong>Status:</strong> <span style="color: ${qualityColor};">${content.status}</span></p>
            <p>${content.message}</p>
          </div>
        `;

      default:
        return `<div class="info-box"><p>Content type: ${contentType}</p></div>`;
    }
  }

  /**
   * Format content section as plain text
   */
  formatContentSectionText(contentType, content) {
    // Simplified text version - can be enhanced
    let text = `\n${contentType.toUpperCase()}\n`;
    text += `${'-'.repeat(30)}\n`;
    
    if (content.available === false) {
      text += `${content.message || 'Data not available'}\n`;
      return text;
    }

    switch (contentType) {
      case 'TotalConsumption':
        text += `Total: ${content.totalConsumption} ${content.unit}\n`;
        text += `Average: ${content.average} ${content.unit}\n`;
        text += `Peak: ${content.peak} ${content.unit}\n`;
        break;
      case 'ConsumptionByRoom':
        if (content.rooms) {
          content.rooms.slice(0, 10).forEach(room => {
            text += `${room.roomName}: ${room.consumption} ${room.unit}\n`;
          });
        }
        break;
      case 'EUI':
        if (content.available) {
          text += `EUI: ${content.eui} ${content.unit}\n`;
        }
        break;
      case 'Anomalies':
        text += `Total: ${content.total}\n`;
        text += `High: ${content.bySeverity.High}, Medium: ${content.bySeverity.Medium}, Low: ${content.bySeverity.Low}\n`;
        break;
      default:
        text += JSON.stringify(content, null, 2) + '\n';
    }
    
    return text + '\n';
  }
}

module.exports = new ReportEmailService();
